version: "3.8"
services:
    buzzer-app:
        build:
            context: ./
        ports:
            - "8090:8090"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"